### ISSUE TITLE
Bug: Map19 is marked as completeable with just the Blue and Yellow keycards

### ISSUE THREAD

**Issue by powerlord** [Ozone31/doomii-ap-tracker#1]
Map19 is completeable if you have the Red + Blue or Red + Yellow keycards, but not the Blue + Yellow keycards.

The red pillar is in the center, so having the other two open doesn't create a wide enough gap on either side to pass through to the exit.

**Comment by Ozone31** [comment]
I just checked this, and in the 0.0.1.0 release the logic works as you said it should - you need the red key plus one of the other colors.

**Comment by HL971** [comment]
I have replicated this issue.
It seems that the tracker is tracking the skull keys incorrectly. In the latest Big Async I have received for The Citadel (Map19) the Blue and Yellow skull keys. The tracker is showing that I have received the Blue and Red skull keys. This has resulted in the tracker incorrectly marking the exit as reachable.
![image](https://github.com/Ozone31/doomii-ap-tracker/assets/9804175/96505025-e3c8-4563-8ec0-1cc3cb25481a)
![image](https://github.com/Ozone31/doomii-ap-tracker/assets/9804175/5995ead4-bd83-4e89-a1dd-2e5726d1a8fb)

**Comment by Ozone31** [comment]
![image](https://github.com/Ozone31/doomii-ap-tracker/assets/137243076/8a075793-24ad-4939-a2aa-eba59412363b)
![image](https://github.com/Ozone31/doomii-ap-tracker/assets/137243076/2b27672c-90ab-46d3-9237-59ec763405cc)
I checked the item mapping against the APWorld, and they do match up. So I'm not sure where the issue is. Are you on the latest version of Poptracker/latest release of this pack?
